Make running with python3.6 working
Avoiding traceback
Traceback (most recent call last):
  File /home/thiblahute/devel/hotdoc/hotdoc/hotdoc/run_hotdoc.py, line 40, in run
    project.setup()
  File /home/thiblahute/devel/hotdoc/hotdoc/hotdoc/core/project.py, line 243, in setup
    self.tree.parse_sitemap(self.change_tracker, sitemap)
  File /home/thiblahute/devel/hotdoc/hotdoc/hotdoc/core/tree.py, line 634, in parse_sitemap
    unlisted_symbols = self.__parse_pages(change_tracker, sitemap)
  File /home/thiblahute/devel/hotdoc/hotdoc/hotdoc/core/tree.py, line 396, in __parse_pages
    self, fname, self.__include_paths)
  File /home/thiblahute/devel/hotdoc/hotdoc/hotdoc/utils/signals.py, line 46, in __call__
    res = func(obj, *args, **kargs)
  File /home/thiblahute/devel/hotdoc/hotdoc/hotdoc/core/extension.py, line 359, in __resolve_placeholder_cb
    self.__find_package_root()
  File /home/thiblahute/devel/hotdoc/hotdoc/hotdoc/core/extension.py, line 402, in __find_package_root
    commonprefix = os.path.commonprefix(self._get_all_sources())
  File /usr/lib/python3.6/genericpath.py, line 76, in commonprefix
    if not isinstance(m[0], (list, tuple)):
TypeError: 'OrderedSet' object does not support indexing
FAILED: gstreamer-libs-1.0-doc